using System;
using System.Text;
using System.IO;
using System.Reflection;
using Shone;

namespace Test
{
    public class TestApp
    {
        static string dir = @"C:\Hjx\Shone2020\Shone.Math\Src\AutoGenerated\";
        static void Main(string[] args)
        {
            MyCode.AutoGenerate();

            Console.WriteLine();
            Console.WriteLine(Math<float>.PI);
            Console.WriteLine(Math<float>.Pow(5, 3));
            Console.WriteLine();
            Console.ReadKey();
        }
    }
}
